- name: Ensure Container Networking Interface plugins directory {{ cni_dir }} exists
  file:
    path: "{{ cni_dir }}"
    state: directory
    recurse: yes
  become: yes

- name: Ensure Kube config directory {{ kube_config_dir }} exists
  file:
    path: "{{ kube_config_dir }}"
    state: directory
    recurse: yes
  become: yes

- name: Download CNI plugins
  unarchive:
    src: "{{ cni_plugin_location }}"
    dest: "{{ cni_dir }}"
    copy: no
  become: yes

- name: Download Kubernetes worker binaries
  get_url:
    url: "{{ kubernetes_binaries_base_url }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ kubectl_server_binary }}"
    - "{{ kube_proxy_binary }}"
    - "{{ kubelet_binary }}"

- name: Copy Kube config
  template:
    src: "kubeconfig.j2"
    dest: "{{ kube_config_dir }}/kubeconfig"
  become: yes

- name: Copy Kubernetes worker systemd services
  template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
  become: yes
  with_items:
    - "kube-proxy"
    - "kubelet"

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Enable Kubernetes worker systemd services
  command: systemctl enable {{ item }}
  become: yes
  with_items:
    - "kube-proxy"
    - "kubelet"

- name: Start Kubernetes worker systemd services
  command: systemctl start {{ item }}
  become: yes
  with_items:
    - "kube-proxy"
    - "kubelet"
